### ISSUE TITLE
Servo error at 68deg, jumps to 180deg

### ISSUE THREAD

**Issue by MattAtKitronik** [KitronikLtd/pxt-kitronik-I2C-16-servo#2]
Sweeping a servo through 45 degrees encountered an error when passing 68 degrees, causing the servo to jump to 180 degrees. Tested by moving the servo by 1-degree increments to confirm the error occurs at an angle of 68 degrees.

**Comment by AlasdairAtKitronik** [comment]
The issue relates to the change in MakeCode from integer mathematics to floating point mathematics. By altering a small part of the servo write code, this issue has been resolved.
